[package]
name = "rusty_painter"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.24.6"
fltk = { version = "^1.4.1", features = ["fltk-bundled"] }
rust-embed = "8.3.0"
